### ISSUE TITLE
Converting this XML to C# class fails

### ISSUE THREAD

**Issue by XTR-KyleWilkins** [Json2CSharp/XmlToCSharp#18]
when attempting to convert the XML below it fails though I don't have an error that it is throwing.

Only the "Use Pascal case" option is selected.

```
<GetLegalPartyRolesResponse xmlns="http://manatron.com/recordswsapi/">
  <GetLegalPartyRolesResult>
	<GRMLegalPartyRole>
	  <LegalPartyRoleId>75</LegalPartyRoleId>
	  <LegalPartyId>81</LegalPartyId>
	  <DisplayName>MR. OYEBAMIJI OLAJIDE</DisplayName>
	  <NamePrefix>        </NamePrefix>
	  <FirstName>OYEBAMIJI                       </FirstName>
	  <MiddleName>                                </MiddleName>
	  <LastName>OLAJIDE                                                         </LastName>
	  <NameSfx>        </NameSfx>
	  <Confidential>false</Confidential>
	  <LegalPartyType>Individual</LegalPartyType>
	  <LegalPartyRoleType>Owner</LegalPartyRoleType>
	  <PrimaryOwner>false</PrimaryOwner>
	  <PercentOfOwnership>100.0000000000</PercentOfOwnership>
	  <OwnershipType>SOLE</OwnershipType>
	  <AccountId>95</AccountId>
	  <MailingAddresses>
		<GRMMailingAddress>
		  <City>OBAWOLE</City>
		  <State>LG</State>
		  <PostalCd>IFK2690-99</PostalCd>
		  <Predirectional>Individual</Predirectional>
		  <StreetName>Individual</StreetName>
		  <StreetType>Individual</StreetType>
		  <Postdirectional>Individual</Postdirectional>
		  <UnitType>Individual</UnitType>
		  <UnitNumber>Individual</UnitNumber>
		  <AddrUnits>Individual</AddrUnits>
		  <CommId>81</CommId>
		  <CorrespondenceType>Default</CorrespondenceType>
		  <USPSAddressType>Standard</USPSAddressType>
		  <AddlAddrLine>Individual</AddlAddrLine>
		  <AttentionLine>Individual</AttentionLine>
		  <StreetNumber>0</StreetNumber>
		  <Recipient>MR. OYEBAMIJI OLAJIDE</Recipient>
		  <DeliveryAddress>Individual</DeliveryAddress>
		  <LastLine>OBAWOLE LG  IFK2690-99</LastLine>
		  <Country>NIGERIA</Country>
		  <BegMonthDay>0101</BegMonthDay>
		  <EndMonthDay>1231</EndMonthDay>
		  <DefaultAddress>false</DefaultAddress>
		  <NumberOrAddress>Individual</NumberOrAddress>
		  <AddrNumberPrefix>Individual</AddrNumberPrefix>
		  <AddrNumberSuffix>Individual</AddrNumberSuffix>
		</GRMMailingAddress>
	  </MailingAddresses>
	</GRMLegalPartyRole>
  </GetLegalPartyRolesResult>
</GetLegalPartyRolesResponse>
```

**Comment by TristBella** [comment]
it appears any XML fails at this point

**Comment by TristBella** [comment]
> when attempting to convert the XML below it fails though I don't have an error that it is throwing.
> 
> Only the "Use Pascal case" option is selected.
> 
> ```
> <GetLegalPartyRolesResponse xmlns="http://manatron.com/recordswsapi/">
>   <GetLegalPartyRolesResult>
> 	<GRMLegalPartyRole>
> 	  <LegalPartyRoleId>75</LegalPartyRoleId>
> 	  <LegalPartyId>81</LegalPartyId>
> 	  <DisplayName>MR. OYEBAMIJI OLAJIDE</DisplayName>
> 	  <NamePrefix>        </NamePrefix>
> 	  <FirstName>OYEBAMIJI                       </FirstName>
> 	  <MiddleName>                                </MiddleName>
> 	  <LastName>OLAJIDE                                                         </LastName>
> 	  <NameSfx>        </NameSfx>
> 	  <Confidential>false</Confidential>
> 	  <LegalPartyType>Individual</LegalPartyType>
> 	  <LegalPartyRoleType>Owner</LegalPartyRoleType>
> 	  <PrimaryOwner>false</PrimaryOwner>
> 	  <PercentOfOwnership>100.0000000000</PercentOfOwnership>
> 	  <OwnershipType>SOLE</OwnershipType>
> 	  <AccountId>95</AccountId>
> 	  <MailingAddresses>
> 		<GRMMailingAddress>
> 		  <City>OBAWOLE</City>
> 		  <State>LG</State>
> 		  <PostalCd>IFK2690-99</PostalCd>
> 		  <Predirectional>Individual</Predirectional>
> 		  <StreetName>Individual</StreetName>
> 		  <StreetType>Individual</StreetType>
> 		  <Postdirectional>Individual</Postdirectional>
> 		  <UnitType>Individual</UnitType>
> 		  <UnitNumber>Individual</UnitNumber>
> 		  <AddrUnits>Individual</AddrUnits>
> 		  <CommId>81</CommId>
> 		  <CorrespondenceType>Default</CorrespondenceType>
> 		  <USPSAddressType>Standard</USPSAddressType>
> 		  <AddlAddrLine>Individual</AddlAddrLine>
> 		  <AttentionLine>Individual</AttentionLine>
> 		  <StreetNumber>0</StreetNumber>
> 		  <Recipient>MR. OYEBAMIJI OLAJIDE</Recipient>
> 		  <DeliveryAddress>Individual</DeliveryAddress>
> 		  <LastLine>OBAWOLE LG  IFK2690-99</LastLine>
> 		  <Country>NIGERIA</Country>
> 		  <BegMonthDay>0101</BegMonthDay>
> 		  <EndMonthDay>1231</EndMonthDay>
> 		  <DefaultAddress>false</DefaultAddress>
> 		  <NumberOrAddress>Individual</NumberOrAddress>
> 		  <AddrNumberPrefix>Individual</AddrNumberPrefix>
> 		  <AddrNumberSuffix>Individual</AddrNumberSuffix>
> 		</GRMMailingAddress>
> 	  </MailingAddresses>
> 	</GRMLegalPartyRole>
>   </GetLegalPartyRolesResult>
> </GetLegalPartyRolesResponse>
> ```

try going to the link on the main page.....it worked

**Comment by XTR-KyleWilkins** [comment]
Would an internet connection speed affect it? I'm out in the boonies at the moment.

**Comment by dancase79** [comment]
I don't it's a connection speed issue. I'm experiencing the same issue, using a Fibre connection with 113MB up and 30mb down.

**Comment by ghost** [comment]
apologies this is a mistake from my end, i accidentally delete a storage account that is linked to this service, thanks everyone for letting me know
