### ISSUE TITLE
Don't remove Capoo. When I turned off adblock, Capoo is gone. Make him happy and alive! 💔

### ISSUE THREAD

**Issue by ArtemVolsh** [Json2CSharp/XmlToCSharp#21]

**Comment by ArtemVolsh** [comment]
Here's Capoo with AdBlock
![image](https://user-images.githubusercontent.com/77543991/229093136-f21bbe5a-bd67-4fe0-8ca5-fc2cde6f706e.png)
No Capoo on turned off AdBlock
![image](https://user-images.githubusercontent.com/77543991/229093230-27c31ba1-8fdb-4554-8c96-4bd6ed45a19b.png)

**Comment by ghost** [comment]
Haha Don't worry capoo is happy and alive again :3 he's just taking a kitty slumber
